package Lexico;

public enum Gramatica {
	// TIPOS DE ANALISADORES LEXICOS
	EOF,
	TIPOINT,
	TIPOFLOAT,
	TIPOCHAR,
	IDENTIFICADOR,
	
	//OPERADORES REALCIONAIS
	OPERADOR_RELACIONAL_MAIOR,
	OPERADOR_RELACIONAL_MAIORIGUAL,
	OPERADOR_RELACIONAL_MENOR,
	OPERADOR_RELACIONAL_MENORIGUAL,
	OPERADOR_RELACIONAL_IGUAL,
	OPERADOR_RELACIONAL_DIFERENCA,
	
	// OPERADORES ARITMETICOS
	OPERADOR_ARITMETICO_ATRIBUICAO,
	OPERADOR_ARITMETICO_SOMA,
	OPERADOR_ARITMETICO_SUBTRACAO,
	OPERADOR_ARITMETICO_DIVISAO,
	OPERADOR_ARITMETICO_MULTIPLICACAO,
	
	// OPERADORES ESPECIAIS
	CARACTER_ESPECIAL_ABREPARENTESES,
	CARACTER_ESPECIAL_FECHAPARENTESES,
	CARACTER_ESPECIAL_ABRECHAVE,
	CARACTER_ESPECIAL_FECHACHAVE,
	CARACTER_ESPECIAL_PONTOVIRGULA,
	CARACTER_ESPECIAL_VIRGULA,
	
	// PALAVRAS RESERVADAS
	PALAVRA_RESERVADA_MAIN,
	PALAVRA_RESERVADA_IF,
	PALAVRA_RESERVADA_ELSE,	
	PALAVRA_RESERVADA_WHILE,
	PALAVRA_RESERVADA_DO,
	PALAVRA_RESERVADA_FOR,
	PALAVRA_RESERVADA_INT,
	PALAVRA_RESERVADA_FLOAT,
	PALAVRA_RESERVADA_CHAR,


	PALAVRA_RESERVADA_ABSTRACT,
    PALAVRA_RESERVADA_AS,
    PALAVRA_RESERVADA_BASE,
    PALAVRA_RESERVADA_BOOL,
    PALAVRA_RESERVADA_BREAK,
    PALAVRA_RESERVADA_BYTE,
    PALAVRA_RESERVADA_CASE,
    PALAVRA_RESERVADA_CATCH,
    PALAVRA_RESERVADA_CHECKED,
    PALAVRA_RESERVADA_CLASS,
    PALAVRA_RESERVADA_CONST,
    PALAVRA_RESERVADA_CONTINUE,
    PALAVRA_RESERVADA_DECIMAL,
    PALAVRA_RESERVADA_DEFAULT,
    PALAVRA_RESERVADA_DELEGATE,
    PALAVRA_RESERVADA_FALSE,
    PALAVRA_RESERVADA_FINALLY,
    PALAVRA_RESERVADA_FIXED,
    PALAVRA_RESERVADA_FOREACH,
    PALAVRA_RESERVADA_GOTO,
    PALAVRA_RESERVADA_IMPLICIT,
    PALAVRA_RESERVADA_IN,
    PALAVRA_RESERVADA_INTERFACE,
    PALAVRA_RESERVADA_INTERNAL,
    PALAVRA_RESERVADA_SIZEOF,
    PALAVRA_RESERVADA_LOCK,
    PALAVRA_RESERVADA_LONG,
	PALAVRA_RESERVADA_IS,
	PALAVRA_RESERVADA_DOUBLE,
	PALAVRA_RESERVADA_ENUM,
	PALAVRA_RESERVADA_EVENT,
	PALAVRA_RESERVADA_EXPLICIT,
	PALAVRA_RESERVADA_EXTERN,
	PALAVRA_RESERVADA_PUBLIC,
	PALAVRA_RESERVADA_PRIVATE,
	PALAVRA_RESERVADA_STATIC,

	
	FIMLEXICO,
	
	}
