package Lexico;

public enum Gramatica {
	// TIPOS DE ANALISADORES LEXICOS
	EOF,
	TIPOINT,
	TIPOFLOAT,
	TIPOCHAR,
	IDENTIFICADOR,
	
	//OPERADORES REALCIONAIS
	OPERADOR_RELACIONAL_MAIOR,
	OPERADOR_RELACIONAL_MAIORIGUAL,
	OPERADOR_RELACIONAL_MENOR,
	OPERADOR_RELACIONAL_MENORIGUAL,
	OPERADOR_RELACIONAL_IGUAL,
	OPERADOR_RELACIONAL_DIFERENCA,
	
	// OPERADORES ARITMETICOS
	OPERADOR_ARITMETICO_ATRIBUICAO,
	OPERADOR_ARITMETICO_SOMA,
	OPERADOR_ARITMETICO_SUBTRACAO,
	OPERADOR_ARITMETICO_DIVISAO,
	OPERADOR_ARITMETICO_MULTIPLICACAO,
	
	// OPERADORES ESPECIAIS
	CARACTER_ESPECIAL_ABREPARENTESES,
	CARACTER_ESPECIAL_FECHAPARENTESES,
	CARACTER_ESPECIAL_ABRECHAVE,
	CARACTER_ESPECIAL_FECHACHAVE,
	CARACTER_ESPECIAL_PONTOVIRGULA,
	CARACTER_ESPECIAL_VIRGULA,
	
	// PALAVRAS RESERVADAS
	PALAVRA_RESERVADA_MAIN,
	PALAVRA_RESERVADA_IF,
	PALAVRA_RESERVADA_ELSE,	
	PALAVRA_RESERVADA_WHILE,
	PALAVRA_RESERVADA_DO,
	PALAVRA_RESERVADA_FOR,
	PALAVRA_RESERVADA_INT,
	PALAVRA_RESERVADA_FLOAT,
	PALAVRA_RESERVADA_CHAR,
	
	FIMLEXICO,
	
	}
